// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var SquareVerifier = artifacts.require('Verifier');

contract('SquareVerifier', accounts => {
    const account_one = accounts[0];

    describe('Verification', function () {
        beforeEach(async function () {
            verifier = await SquareVerifier.new({from: account_one});
        })

        it('should verify those values', async function () {
            // assert.equal(verifier, !undefined, 'contract executed successfully');
        })
    });
})
